version: '3.6'
services:
  influxdb:
    healthcheck:
      test: influx ping || exit 1
      interval: 3s
      timeout: 5s
      retries: 5
    platform: linux/x86_64
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=mytestuser123!
      - DOCKER_INFLUXDB_INIT_PASSWORD=mytestuser123!
      - DOCKER_INFLUXDB_INIT_ORG=my_test_org
      - DOCKER_INFLUXDB_INIT_BUCKET=test
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=c2hhbG9tX3JhbXpp
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: {}
