AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Metis metadata collector
Parameters:
  ClusterName:
    Type: String
    Description: The name of the ECS cluster
    AllowedPattern: "[\\w-]+"
    MinLength: '1'
    ConstraintDescription: The name must contain only lowercase letters, numbers, underscores and hyphens.
    Default: metis-collector
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet(s) where ECS task will run
    MinLength: '1'
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The security group(s) of the ECS task
    MinLength: '1'
  MetisAPIKey:
    Type: String
    Description: Your API Key for Metis
    MinLength: '1'
  ConnectionStrings:
    Type: String
    Description: Connection string(s) to your production DB, separated by a semicolon (;)
    AllowedPattern: "[^ ]+"
    ConstraintDescription: Connection strings cannot contain spaces.
    MinLength: '1'
    NoEcho: true
  AgentEnvironment:
    Type: "String"
    Description: Choose non-production to enable slow-query-log, refer the database setup here https://github.com/metis-data/slow-query-log
    AllowedValues: [ "production", "non-production" ]
  MetisEnvironment:
    Type: "String"
    Description: environment in which the MMC is running
    AllowedValues: [ "cloud", "prem" ]
  AwsAccessKeyId:
    Type: "String"
    Description: aws access key id
  AwsSecretAccessKey:
    Type: "String"
    Description: aws secret access key
  AwsRegion:
    Type: "String"
    Description: aws region
  ProviderMetadata:
    Type: "String"
    Description: json string format of an array of objects in the following convention [{"resource":"","instance_id":"","provider":""}]
Resources:
  ConnectionStringSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ['-', [metis-connection-strings, !Ref ClusterName]]
      Description: "This secret contains the connection string for Metis Production Metadata Collector (including usernames and passwords)."
      SecretString: !Ref ConnectionStrings
    DeletionPolicy: Delete
  ConnectionStringSecretPolicy: # Based on https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples.html
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref ConnectionStringSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
        - Resource: !Ref ConnectionStringSecret
          Action: secretsmanager:GetSecretValue
          Effect: Allow
          Principal:
            AWS: !GetAtt MetisMDCollectorRole.Arn
  MetisMDCollectorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: MetisECSTaskExecutionRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "ec2:DescribeSubnets"
                Resource: "*"
        - PolicyName: MetisECSTaskExecutionRolePolicy2
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "ec2:DescribeSubnets"
                Resource: "*"
    DeletionPolicy: Delete
  MetisMDCollectorCluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterName: !Ref ClusterName
    DeletionPolicy: Delete
  MetisMDCollector:
    DeletionPolicy: Delete
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: public.ecr.aws/o2c0x5x8/metis-md-collector:latest
          Name: metis-md-collector
          Environment:
            - Name: APP_ENV
              Value: staging
            - Name: API_GATEWAY_HOST
              Value: ingest-stg.metisdata.io
            - Name: API_GATEWAY_PATH
              Value: /md-collector
            - Name: API_GATEWAY_PORT
              Value: 443
            - Name: WEB_APP_HOST
              Value: dev.metisdata.io
            - Name: WEB_APP_PORT
              Value: 443
            - Name: API_KEY
              Value: !Ref MetisAPIKey
            - Name: CONNECTION_STRINGS_SECRET
              Value: !Ref ConnectionStringSecret
            - Name: METIS_ENVIRONMENT
              Value: !Ref MetisEnvironment
            - Name: AGENT_ENVIRONMENT
              Value: !Ref AgentEnvironment
            - Name: METIS_AWS_ACCESS_KEY_ID
              Value: !Ref AwsAccessKeyId
            - Name: METIS_AWS_SECRET_ACCESS_KEY
              Value: !Ref AwsSecretAccessKey
            - Name: METIS_AWS_REGION
              Value: !Ref AwsRegion
            - Name: METIS_PROVIDER_METADATA
              Value: !Ref ProviderMetadata
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Join ['', ['/ecs/', !Ref ClusterName]]
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
              awslogs-create-group: true
      Cpu: '256'
      Memory: '512'
      # The task definition's name is suffixed with the cluster name, to allow multiple tasks with different parameters (e.g. different VPCs)
      Family: !Join ['-', [metis-md-collector, !Ref ClusterName]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
      TaskRoleArn: !GetAtt MetisMDCollectorRole.Arn
      ExecutionRoleArn: !GetAtt MetisMDCollectorRole.Arn
  MetisMDCollectorService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MetisMDCollectorCluster
      LaunchType: FARGATE
      DesiredCount: 1  # You can adjust the desired number of tasks as needed
      TaskDefinition: !Ref MetisMDCollector
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIds
          Subnets: !Ref SubnetIds