{
 "title": "Metis RDS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbInstance",
    "query": {
     "query": "label_values(dimension_DBInstanceIdentifier)"
    }
   },
   { "name": "apiKey", "query": { "query": "label_values(apikey)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "options": {
    "content": "[![metis](https://static-asserts-public.s3.eu-central-1.amazonaws.com/metis-min-logo.png)](https://app.metisdata.io/)\n"
   }
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "DB Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_maximum{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_rds_read_latency_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Avg: {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "aws_rds_read_latency_maximum{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Max: {{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_rds_write_latency_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Avg: {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "aws_rds_write_latency_maximum{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Max: {{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_disk_queue_depth_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Avg: {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "aws_rds_disk_queue_depth_maximum{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Max: {{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "aws_rds_swap_usage_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "{{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Read / Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Read: {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "aws_rds_write_throughput_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Write: {{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Read / Write IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Read: {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "aws_rds_write_iops_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Write: {{dimension_DBInstanceIdentifier}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "aws_rds_network_receive_throughput_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "In: {{dimension_DBInstanceIdentifier}}"
    },
    {
     "expr": "aws_rds_network_transmit_throughput_average{dimension_DBInstanceIdentifier=~\"$dbInstance\"}",
     "legendFormat": "Out: {{dimension_DBInstanceIdentifier}}"
    }
   ]
  }
 ]
}