app:
  api_key:
  queryTimeoutInMilliseconds: 5000
  web_app_url: ''
  db_connection_strings:
  sentry_dsn: 'https://51701d0b4836486eaa874b522dc2fecb@o1173646.ingest.sentry.io/6515773'
  datadog_api_key: 'pubdd790745e9883748e503f312d8cc7197'
  ignore_current_time: 'false'
  ignoreWinstonConsole: 'false'
  aws:
    aws_region: eu-central-1
    request:
      options:
        headers:
          x-api-key:
        api_gateway_method`: 'POST'
        https_timeout: 30000
        api_gateway_host: 'ingest-stg.metisdata.io'
        api_gateway_port: '443'
        api_gateway_path: '/md-collector'

queries:
  # The extracted name of the schema and table MUST be "schema" and "table", respectively.
  tables_size:
    query:
      SELECT
      n.nspname AS schema, c.relname AS table, relpages AS pages, reltuples AS rows,
      pg_relation_size(c.oid) / 1024 AS relation_size, pg_table_size(c.oid) / 1024 AS table_size,
      pg_indexes_size(c.oid) / 1024 AS indexes_size,
      (pg_total_relation_size(c.oid) - pg_relation_size(c.oid) - pg_indexes_size(c.oid)) / 1024 AS toast_size
      FROM pg_class AS c
      LEFT JOIN pg_namespace AS n
      ON (N.oid = c.relnamespace)
      WHERE relkind='r'
      AND n.nspname NOT IN ('pg_catalog', 'information_schema')
      ORDER BY 1, 2;
    times_a_day: '1'
  index_usage:
    query:
      SELECT
      sui.schemaname AS schema, sui.relid, sui.relname AS table, sui.indexrelid, sui.indexrelname AS index,
      sui.idx_scan AS index_scans, sui.idx_tup_read AS index_rows_reads, sui.idx_tup_fetch AS index_rows_writes,
      sio_ui.idx_blks_read AS pages_read_from_disk, sio_ui.idx_blks_hit AS pages_read_from_buffer
      FROM pg_stat_user_indexes AS sui
      JOIN pg_statio_user_indexes AS sio_ui
      ON sui.relid = sio_ui.relid
      AND sui.indexrelid = sio_ui.indexrelid;
    times_a_day: '6'
