version: '3'
services:
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: influxdb:2.7.1-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-my-bucket}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-my-password}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  telegraf:
    image: telegraf:1.27-alpine
    container_name: telegraf
    restart: unless-stopped
    command: telegraf --config /etc/telegraf/telegraf.conf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
    - '8125:8125'

  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
      - '4000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
volumes:
  influxdb-storage:
  grafana-storage:
