instances:
  - region: eu-central-1
    instance: database-2
    disable_enhanced_metrics: false
    labels:
      apikey: bar
  # - region: us-east-1
  #   instance: rds-mysql57
  #   aws_access_key: AKIAIOSFODNN7EXAMPLE
  #   aws_secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   aws_role_arn: arn:aws:iam::76784568345:role/my-role
  #   disable_basic_metrics: true
  #   disable_enhanced_metrics: false
  #   labels:
  #     foo: bar
  #     baz: qux