version: '3'
services:
  yace:
    image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.53.0
    restart: unless-stopped
    container_name: yace
    ports:
      - '8080:8080'
    expose:
      - 8080
    command:
      - -listen-address=:8080
      - -config.file=/tmp/config.yml
    volumes:
      - '$HOME/.aws/credentials:/exporter/.aws/credentials:ro'
      - ./yace.yaml:/tmp/config.yml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge