name: Build and deploy docker image
on:
  push:
    branches: [ "main" ]
    paths:
      - client-agent/src/**
  workflow_dispatch:
jobs:
  deploy_docker:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client-agent/src
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::357242092635:role/github-action-metis-production-agent
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1.5.1
        with:
          registry-type: public
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true  # Ignore the failure of a step and avoid terminating the job.
      - name: build and deploy
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          ID=$(docker build \
            --build-arg NPM_TOKEN_READ_ONLY=${{ secrets.NPM_TOKEN_READ_ONLY }} \
            --build-arg DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }} \
            --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            -q -t $REGISTRY/o2c0x5x8/metis-md-collector .)
          
          docker tag $ID $REGISTRY/o2c0x5x8/metis-md-collector:$TAG
          docker tag $ID $REGISTRY/o2c0x5x8/metis-md-collector:latest
          
          docker push $REGISTRY/o2c0x5x8/metis-md-collector:$TAG
          docker push $REGISTRY/o2c0x5x8/metis-md-collector:latest
      - name: create cloud formation
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          cat ../../metadata-collector-cloudformation.yaml | sed -e 's/ingest.metisdata.io/ingest-stg.metisdata.io/g' -e 's/app.metisdata.io/dev.metisdata.io/g' -e 's/Value: production/Value: staging/g' > ../../metadata-collector-cloudformation-stg.yaml
          cp ../../metadata-collector-cloudformation-stg.yaml .
      - name: upload artifact
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: cloudformation.yaml
          path: metadata-collector-cloudformation-stg.yaml
